name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SOLANA_CLI_VERSION: "2.3.11"
  RUST_TOOLCHAIN: "1.90.0"

jobs:
  test-rust:
    name: ${{ matrix.example }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example:
          - create-and-update
          - counter/native
          - counter/pinocchio
          - account-comparison
          - zk-id
          - basic-operations/native
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          example: ${{ matrix.example }}
          solana-cli-version: ${{ env.SOLANA_CLI_VERSION }}
          rust-toolchain: ${{ env.RUST_TOOLCHAIN }}
          install-circom: ${{ matrix.example == 'zk-id' }}

      - name: Setup ZK circuits
        if: matrix.example == 'zk-id'
        working-directory: ${{ matrix.example }}
        run: ./scripts/setup.sh

      - name: Build and test
        working-directory: ${{ matrix.example }}
        run: cargo test-sbf
